NAME = ft_display_file
SRC = ft_display_file.c
CC = cc
FLAGS = -Wall -Wextra -Werror
RM = rm -f
all:
	$(CC) $(FLAGS) $(SRC) -o $(NAME)
clean:
	$(RM) *.o
fclean: clean
	$(RM) $(NAME)
.PHONY: all clean fclean

